version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  app:
    build: ./../../
    command: flask run --host 0.0.0.0 --port 5000
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - ./.env.dev
      - ./.env.custom

volumes:
  data:
